#!/usr/bin/python3
import cgi
import subprocess as sp
print("conetnt-type: text/html")
print()
w=cgi.FieldStorage()
option=w.getvalue("x")
imp=w.getvalue("y")
if imp=="run":
    op=sp.getoutput(f"sudo docker run -dit {option}")
    fil=open("/var/www/html/data.html","w")
    print(op)
    fil.write(op)
    fil.close()
elif (imp == 'images'):
    op=sp.getoutput(f"sudo docker images")
    fil=open('/var/www/html/data.html','w')
    fil.write(op)
    fil.close()
elif (imp=='ps'):
    op=sp.getoutput(f"sudo docker ps")
    fil=open('/var/www/html/data.html','w')
    fil.write(op)
    fil.close()
elif imp=='psa':
    op=sp.getoutput(f"sudo docker ps -a")
    fil=open('/var/www/html/data.html','w')
    fil.write(op)
    fil.close()
elif imp=='start':
    op=sp.getoutput(f"sudo docker start {option}")
    fil=open('/var/www/html/data.html','w')
    fil.write(op)
    fil.close()
elif imp=='stop':
    op=sp.getoutput(f"sudo docker stop {option}")
    fil=open('/var/www/html/data.html','w')
    fil.write(op)
    fil.close()
elif imp=='exec':
    op=sp.getoutput(f"sudo docker exec {option}")
    fil=open('/var/www/html/data.html','w')
    fil.write(op)
    fil.close()
else:
    fil=open('/var/www/html/data.html','w')
    fil.write(" ")
    fil.close()


